[project]
name = "mirage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow>=12.0.0",
    "pygobject>=3.54.5",
    "qrcode>=8.2",
    "ruff>=0.14.3",
]
